import localFont from "next/font/local";
import "./globals.css";
import CardCategory from "@/components/CardCategory";
import { SideBarList } from "../constant/SideBarMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex">
          <aside className="w-64 bg-white text-primary p-4 border-r border-gray-200">
            <ul>
              {SideBarList.map((item) => (
                <CardCategory key={item} item={item} />
              ))}
            </ul>
          </aside>
          <main className="flex-1 bg-white p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
